version: "3.9"
networks:
  web:
    external: true
  internal:
    external: false
services:
  app_url:
    build: ./
    image: missael-dev-url-shrinker
    environment:
      - MONGO_URL=mongodb://db:27017/test
      - PORT=5000
    networks:
      - internal
      - web
    ports:
      - "5000:5000"
  db:
    image: mongo:5-focal
    networks:
      - internal
      - web