version: "3.9"
networks:
  web:
    external: true
  internal:
    external: false
services:
  app_url:
    build: .
    image: missael-dev-url-shrinker
    depends_on:
      - db
    labels:
      - traefik.backend=url-shrinker
      - traefik.frontend.rule=Host:l.missael.dev
      - traefik.docker.network=web
      - traefik.port=5000
    environment:
      - MONGO_URL=mongodb://db:27017/url-shinker
      - PORT=5000
    networks:
      - internal
      - web
    ports:
      - "5000:5000"
  db:
    image: mongo:5-focal
    networks:
      - internal
      - web
    volumes:
      - mongo:/data/db
volumes:
  mongo: